services:
  _defaults:
    public: true

  ceneo_xml.db:
    class: Db
    public: true
    factory: [ 'Db', 'getInstance' ]

  mapping_form_type:
    class: 'CeneoXml\Form\Type\MappingForm'
    arguments:
      - "@=service('prestashop.adapter.legacy.context').getLanguages()"
      - "@=service('choice_provider.ceneo_category').getChoices()"
    tags:
      - { name: form.type } #special tag for form is needed!!!!
    public: true
  attribute_mapping_form_type:
    class: 'CeneoXml\Form\Type\AttributeMappingForm'
    arguments:
      - "@=service('prestashop.adapter.legacy.context').getLanguages()"
      - "@=service('choice_provider.ceneo_attribute').getChoices()"
    tags:
      - { name: form.type } #special tag for form is needed!!!!
    public: true
  choice_provider.ceneo_category:
    class: CeneoXml\Form\ChoiceProvider\CeneoCategoryChoiceProvider
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  choice_provider.ceneo_attribute:
    class: CeneoXml\Form\ChoiceProvider\CeneoAttributeChoiceProvider
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
  ceneo_category:
    class: 'CeneoXml\Repository\CeneoCategoryRepository'
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
      - '@=service("prestashop.adapter.legacy.context").getLanguages(true, service("prestashop.adapter.shop.context").getContextShopID())'
      - '@translator'
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"
  ceneo_attribute:
    class: 'CeneoXml\Repository\CeneoAttributeRepository'
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
      - '@=service("prestashop.adapter.legacy.context").getLanguages(true, service("prestashop.adapter.shop.context").getContextShopID())'
      - '@translator'
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"
  mapping:
    class: 'CeneoXml\Repository\MappingRepository'
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
      - '@=service("prestashop.adapter.legacy.context").getLanguages(true, service("prestashop.adapter.shop.context").getContextShopID())'
      - '@translator'
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"
  attribute_mapping:
    class: 'CeneoXml\Repository\AttributeMappingRepository'
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
      - '@=service("prestashop.adapter.legacy.context").getLanguages(true, service("prestashop.adapter.shop.context").getContextShopID())'
      - '@translator'
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"




  # Grid services
  ceneo_xml.grid.definition.factory.products:
    class: 'CeneoXml\Grid\Definition\Factory\ProductGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true

  ceneo_xml.grid.query_builder.product:
    class: 'CeneoXml\Grid\Query\ProductQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id_shop_group"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.getGroup().share_stock"
      - '@prestashop.core.grid.query.filter.doctrine_filter_applicator'
      - '@prestashop.adapter.legacy.configuration'


  ceneo_xml.grid.data_provider.products:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    public: true
    arguments:
      - '@ceneo_xml.grid.query_builder.product'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'product'

  ceneo_xml.grid.factory.products:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    public: true
    arguments:
      - '@ceneo_xml.grid.definition.factory.products'
      - '@ceneo_xml.grid.data_provider.products'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'

  ceneo_xml.repository.product:
    class: 'CeneoXml\LegacyProductSettingsRepository'
    arguments:
      - '@ceneo_xml.db'
      - "@=service('prestashop.adapter.legacy.context').getContext().shop"
      - '@translator'


  ceneo_xml.form.visibility_form:
    class: 'CeneoXml\Form\Type\VisibilityForm'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  ceneo_xml.form.availability_status_form:
    class: 'CeneoXml\Form\Type\AvailabilityStatusForm'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }
